name: Daily StackOverflow ETL

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  run_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Оновлюємо версію Python, щоб прибрати Warning
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pandas requests google-cloud-bigquery pyarrow pandas-gbq db-dtypes

      # Більш надійний спосіб створити JSON файл (зберігає лапки)
      - name: Create credentials file
        shell: bash
        env:
          GCP_KEYS: ${{ secrets.GCP_KEYS }}
        run: |
          echo "$GCP_KEYS" | base64 --decode > credentials.json

      - name: Run ETL script
        env:
          GOOGLE_APPLICATION_CREDENTIALS: credentials.json
        run: python etl_start.py